[package]
name = "meili-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.35.0", features = ["full"]}
tokio-postgres = "0.7.10"
meilisearch-sdk = "0.24.3"
serde = "1.0"
serde_yaml = "0.9"
